=== iracleous/xmlDemo/xml_files/customer-ns2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.codehub.gr"
           elementFormDefault="qualified">
 
    <element name="Customers">
        <complexType>
            <sequence>
                <element name="Customer"  minOccurs="0" maxOccurs="200">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="surname" type="string"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== iracleous/xmlDemo/xml_files/customer-ns3.xml
<?xml version="1.0" encoding="UTF-8"?>
     <xt:Customers
            xmlns:xt="https://www.codehub.gr"
            xmlns:xt2="https://www.codehub2.gr"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.codehub.gr customer-ns2.xsd
            https://www.codehub2.gr customer-ns7.xsd" >

       <xt:Customer>
            <xt:name>D</xt:name>
            <xt:surname>I</xt:surname>
        </xt:Customer>
        <xt:Customer>
            <xt:name>A</xt:name>
            <xt:surname>B</xt:surname>
        </xt:Customer>
        <xt:Customer>
            <xt:name>S</xt:name>
            <xt:surname>X</xt:surname>
        </xt:Customer>

    </xt:Customers>
